server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: file-transfer-ws
          uri: lb:ws://file-transfer-service
          predicates:
            - Path=/file-transfer/ws, /file-transfer/ws/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - AuthenticationFilter
        - id: file-transfer-service
          uri: lb://file-transfer-service
          predicates:
            - Path=/api/transfers/**,/api/peers/**
          filters:
            - AuthenticationFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: peer-management-service
          uri: lb://peer-management-service
          predicates:
            - Path=/peers/**,/network/**
          filters:
            - AuthenticationFilter
        - id: file-metadata-service
          uri: lb://file-metadata-service
          predicates:
            - Path=/api/file-metadata/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
